version: "2.29"

services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/count:rw
    entrypoint: ["php","/var/www/count/index.php"]
    user:
      "www-data"